### ISSUE TITLE
Pyright needs to be added to 'dev-install' make instruction.

### ISSUE THREAD

**Issue by synchronizing** [aliev/aioauth#22]
Unsure how one would go about this, but the NPM package `pyright` needs to be added to the `dev-install` `Makefile` instruction. Simply doing `npm install -g pyright` will not suffice as Mac and Linux users require `sudo`, and it would be unknown whether or not the user has `npm` installed to begin with.

My best guess is documenting this is the best way around this. Opening issue as a form of discussion.

**Comment by aliev** [comment]
actually pyrights is only needed for CI in our case:

https://github.com/aliev/aioauth/blob/master/.github/workflows/python-package.yml#L38

If you are using vscode, it will already be installed after installing the official Python extension from Microsoft. so no need to run `make lint` from command line.

We can also think about removing pyright from `make lint` and add it only to CI.

Documenting is also good idea, i think for type checking locally someone might prefer mypy.

**Comment by synchronizing** [comment]
> actually pyrights is only needed for CI in our case:
> 
> https://github.com/aliev/aioauth/blob/master/.github/workflows/python-package.yml#L38

Roger that.

> If you are using vscode, it will already be installed after installing the official Python extension from Microsoft. so no need to run `make lint` from command line.

I have it installed, but it was causing some unwarranted issues on my Mac due to it not being globally installed. Was just documenting the case on Issues so I didn't forget.

> We can also think about removing pyright from `make lint` and add it only to CI.

That's a design choice that is up to you. :)

> Documenting is also good idea, i think for type checking locally someone might prefer mypy.

For sure- I'll be sure to add it on #21 under `Contributing`.

**Comment by aliev** [comment]
@synchronizing I'm closing this issue since I migrated project to mypy :)
