### ISSUE TITLE
About a Third-Party (external) authorization server interface

### ISSUE THREAD

**Issue by TatanParker** [aliev/aioauth#61]
Dear @aliev and cons

Your library is amazing but, as you indeed mentioned is still missing some extra-docs for guidance on implementation.

I just would like to know If you have any example of an Third party implementation interface like typical Google, Microsoft auth ... and so on. The level of class abstractions make me go ahead so slow.

I suppose that the key is in creating an interface of Storage class and methods, to create the correct instance for each desired third party chosen.

Please any help would be amazing man.

**Comment by aliev** [comment]
Hi @TatanParker ! aioauth is only server implementation of oauth2.0 protocol. I think authlib is exactly what you need: https://docs.authlib.org/en/latest/client/starlette.html

**Comment by TatanParker** [comment]
Yes man. You are right. However your framework is fantastic to implement oauth2 protocol for clients. I get the point. Thanks
