### ISSUE TITLE
POST /authorize fails with `Method not allowed` status code

### ISSUE THREAD

**Issue by pedropregueiro** [aliev/aioauth#64]
On the docstring of the `create_authorization_response` method, there's an example using a `POST` request:
https://github.com/aliev/aioauth/blob/ab4f7eab8f6bbbe87007663d50b078e92c92349f/aioauth/server.py#L311-L316

However, the first thing that happens in that same method is the pre-validation that the request method is a `GET`:
https://github.com/aliev/aioauth/blob/ab4f7eab8f6bbbe87007663d50b078e92c92349f/aioauth/server.py#L327

It's not that uncommon to split the `GET /authorize` and `POST /authorize` methods to handle authentication and consent in-between. For my specific use-case, the `GET /authorize` request will redirect the user to a client-side webpage to both handle authentication and app/client consent, and then the webpage would send the info back to the server as a `POST /authorize` request with additional headers proving the user is authenticated and can execute that oauth2 flow.

Let me know if this is outside the scope of the library at the moment. 

## Expected Result

Being able to send a `POST` request to the `create_authorization_response` method.

## Actual Result

Getting a `405` status code with `HTTP method is not allowed` response

## Reproduction Steps

```python
import asyncio

from aioauth.collections import HTTPHeaderDict
from aioauth.config import Settings
from aioauth.requests import Post
from aioauth.requests import Query
from aioauth.requests import Request
from aioauth.server import AuthorizationServer
from aioauth.storage import BaseStorage
from aioauth.types import RequestMethod


class Storage(BaseStorage):
    pass


storage = Storage()
authorization_server = AuthorizationServer(storage)

oauth2_request = Request(
        settings=Settings(INSECURE_TRANSPORT=True),
        method=RequestMethod["POST"],
        headers=HTTPHeaderDict(),
        post=Post(),
        query=Query(),
        url="http://localhost:5001/oauth/authorize",
        user=None,
    )

loop = asyncio.get_event_loop()
result = loop.run_until_complete(authorization_server.create_authorization_response(oauth2_request))
print(result)
loop.close()
```

Result:
```
Response(content={'error': <ErrorType.METHOD_IS_NOT_ALLOWED: 'method_is_not_allowed'>, 'description': 'HTTP method is not allowed.', 'error_uri': ''}, status_code=<HTTPStatus.METHOD_NOT_ALLOWED: 405>, headers={'content-type': 'application/json', 'cache-control': 'no-store', 'pragma': 'no-cache', 'allow': 'GET'})
````

## System Information

```
Python Version (3.9.13):
aioauth Version (1.4.0):
Framework (FastAPI)
```

**Comment by aliev** [comment]
Hi @pedropregueiro, I think you are right, we should remove this restriction. I'll check what I can do with it this weekend

**Comment by aliev** [comment]
@pedropregueiro created PR, could you check?

**Comment by pedropregueiro** [comment]
afk until Wed, let me get back to you then!

**Comment by pedropregueiro** [comment]
I think your example would still fail though, as the `create_authorization_response` would not expect a `POST` request after the login handling, unless I'm missing something.

To be clear, this is the flow I'm looking to implement:

1. `GET api.example.com/authorize?client_id=....`
In this case, the API would redirect the user to the frontend (example.com/apps/auth?client=...) for it to handle a) login/signup and b) grant or deny client consent. For context, our frontend and backend are running on different servers and tech.
2. `POST api.example.com/authorize?client_id=`
After the user grants consent for the app to be installed, the frontend will make the above API call with an Authorization header, query params (client_id, response_type, etc.) and possibly some custom form data. Then, on the backend, we run our own user auth validation first (as you hinted at), but once that's done, I still want to delegate the request to aioauth for validation of the oauth2 flow (check client exists, check grants, create code, etc.) and subsequent redirection (with `code=...`) to the expected redirect uri.
4. `POST /token`
No problems here so far.

This 2-step (GET + POST) flow is supported by the 2 main sync python libs: authlib[1] and oauthlib[2], and also mentioned in the OAuth2 RFC[3]:
> The authorization server MUST support the use of the HTTP "GET" method [[RFC2616](https://www.rfc-editor.org/rfc/rfc2616)] for the authorization endpoint and MAY support the use of the "POST" method as well.

For the record, #65 does seem to somewhat fix this issue for me!

[1] https://docs.authlib.org/en/latest/flask/2/authorization-server.html#server (scroll a bit)
[2] https://oauthlib.readthedocs.io/en/latest/oauth2/server.html#create-your-endpoint-views
[3] https://www.rfc-editor.org/rfc/rfc6749#section-3.1

**Comment by aliev** [comment]
oh yes, you seem to be right. I didn't think about this case (2nd one). Let's then merge #65 ?

> The authorization server MUST support the use of the HTTP "GET" method [[RFC2616](https://www.rfc-editor.org/rfc/rfc2616)] for the authorization endpoint and MAY support the use of the "POST" method as well.

👍🏻

**Comment by pedropregueiro** [comment]
left a comment in the PR, but yeah, seems to work as expected now!

**Comment by aliev** [comment]
@pedropregueiro v1.4.1 was released with this fix
