### ISSUE TITLE
Why a token is needed for `/authorize`?

### ISSUE THREAD

**Issue by Pedram-Parsian** [aliev/aioauth#90]
Hi,

As far as I know (_I'm not an OAuth2 expert, so please let me know if I'm wrong_), the steps for **AuthorizationCodeFlow** should be as:
1. User sends a request using the front channel to `/authorize` with data about the client like `client_id`, `scope`, `redirect_uri`, etc.
2. The authorization server validates the client info and redirects the user to the login page, possibly showing a consent page afterward.
4. If the user successfully logs in and accepts the consent info, he will be redirected back to the application with a `code`.
5. The application makes a back channel request to the authorization server to exchange the `code` for a token at `/token`.

But it looks like you require a token even for the first step (request to `/authorize`):

In the `validate_request` method of `ResponseTypeBase` (inside the `aioauth/response_type.py`), there is this final check which ensures there is a user object in the request:
```python
async def validate_request(self, request: TRequest) -> Client:
    # ...

    if not request.user:
        raise InvalidClientError[TRequest](
            request=request, description="User is not authorized"
        )

    return client
```

and also in the tests of the demo project you provided, you first generate a token and attach it to the request to the `/authroize` URL:
```python
@pytest.mark.asyncio
async def test_authorization_code_flow(
    http_client: TestClient, user: "User", client: "Client"
):
    access_token, _ = get_jwt(user)

    response = await http_client.get(
        "/oauth2/authorize",
        query_string={
            "response_type": "code id_token",
            "client_id": client.client_id,
            "redirect_uri": client.redirect_uris[0],
            "scope": "openid email profile",
            "nonce": "73Ncd3",
        },
        headers={"Authorization": f"Bearer {access_token}"},
        allow_redirects=False,
    )
    
    # ...
```

How can I work around this issue?

Thank you in advance for your help. Please let me know if there's any additional information needed on my end.

**Comment by aliev** [comment]
Hello,

As per the principles of the [Authorization Code Flow](https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow#how-authorization-code-flow-works), users need to be authenticated before initiating requests to the `/authorize` endpoint.

In the example above, indeed, I am explicitly passing the user using their JWT token in the header, indicating to the `/authorize` endpoint that the user is authenticated.

In your scenario, it appears that users should be automatically redirected to the login page from the `/authorize` endpoint in case their session is not active.
